name: alga_frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  animate_do: ^1.7.2
  http: ^0.12.1
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  flutter_signin_button: ^1.0.0
  provider: ^4.1.2
  shared_preferences: ^0.5.7+3
  flutter_spinkit: "^4.1.2"
  flutter_speed_dial: ^1.2.5
  flutter_swiper: ^1.1.6
  curved_navigation_bar: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/gifs/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
